{% set name = "bletchley" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://gitlab.com/manny_cyber_wizard/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: f66ddfc4372b34389ae8e1f795758d304bc76292ed3e5137afc968cd56475fed

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.16.0
    - python

test:
  imports:
    - bletchley
    - bletchley.ciphers
    - bletchley.cryptanalysis

about:
  home: https://gitlab.com/manny_cyber_wizard/bletchley
  license: GNU-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A collection of historical ciphers and cryptanalysis tools
  doc_url: https://gitlab.com/manny_cyber_wizard/bletchley/wikis/home
  dev_url: https://gitlab.com/manny_cyber_wizard/bletchley

extra:
  recipe-maintainers:
    - marcelotrevisani
    - mannycyber
