travis:
  secure:
    BINSTAR_TOKEN: dsJIfei7jz9VeZUaHsz3ZG8+vy/wuH9QU1vj8ENoUeSLfeCz/QymxbR2DcL64/d2PQzgxzck32WC2uC4ezMjNCCQRN51meEkCNhSZ4pKOqWvWzh01xrpGtOyWlco0Q2/tHqJ0z2FGW2LDjg9O7VR/L/55e3RxWfBo0jpJPQdceXmKIxhDtCT9SUJen3RGXLenYbjqPgnlOsZwT2EM+yzc2TmL9iaP7Qc/u4q2qwt1XjmPZ2jT3SN4SbY4MUM4CncDdABNCII5Ylm0fwj1HlIPu2BuzMopG2+WhiXnttipXI+B0Fu/b9ZwRfQPIVPcWhd2HSW6brCy1LLjdv5hIpJMn9SHa2OsmmEBmpDH5dOiiJBWiGy4wL9qWVIcqk80mbATtUE61JT+vRcrRwtIGoNpKuyZa/0F7TaZKGG1jIWkgk+efSbzdkvVpVroF5Haq682cq341FGTivUPcW6anlF3EWNI13jOyqOB6QoC98RB4+gYRg8Qwrqsb8t73+A9tGINVmg10giZ8KYCwKiPx6I8mB53xSNF4ZB5rM57wxjaj8opP2j8VEBLhPDFaN/ISAYGS3+9xGwo354ke/CLBbmQ8nsG8J1OzOjjjecRwnkbkVqssFdCh7NdADwzrgY5e6oox/DDsoICcIeVXT6BztQ3DT1N6OaBxnjG4lS8mvrDKk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
